### ISSUE TITLE
ncnn 版本

### ISSUE THREAD

**Issue by steven-hz** [xiangweizeng/mobile-lpr#19]
请问 ncnn 版本的基准是哪个？
要跨edge设备移植的话，需要ncnn对应上版本

**Comment by xiangweizeng** [comment]
只要模型兼容， 一般就没啥问题， 使用最新版本的ncnn应该是兼容的

**Comment by steven-hz** [comment]
> 只要模型兼容， 一般就没啥问题， 使用最新版本的ncnn应该是兼容的

刚刚试了一下，用到树莓派里面，没有检测到bbox

**Comment by steven-hz** [comment]
> > 只要模型兼容， 一般就没啥问题， 使用最新版本的ncnn应该是兼容的
> 
> 刚刚试了一下，用到树莓派里面，没有检测到bbox
> 一共两个.a mlpr ncnn ，所以有点怀疑与ncnn的版本
> 
> 后面我反过来验证了一下，用最新的ncnn 直接替换你的ncnn在ubuntu可以的。
> 说明与ncnn没关系。。

可能是在mlpr的交叉编译上遇到问题了
