### ISSUE TITLE
能否提供原模型

### ISSUE THREAD

**Issue by lmo-aiot** [xiangweizeng/mobile-lpr#6]
谢谢UP主的工作，lffd、lpc、lprmssd512_voc，这些原模型是否能提供我们测试呢？

**Comment by xiangweizeng** [comment]
其它模型没法提供, lffd 车牌检测官方提供了实现版本,[可参考](https://github.com/YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices/tree/master/license_plate_detection) 不过ncnn格式是开源的,可以按需转换

**Comment by JustinLJun** [comment]
好的，谢谢up主
