### ISSUE TITLE
问一下识别模型是自己设计的么？还是基于某个模型改的？

### ISSUE THREAD

**Issue by pycoco** [xiangweizeng/mobile-lpr#7]

**Comment by xiangweizeng** [comment]
基于[ caffe_ocr](https://github.com/senlinuc/caffe_ocr), 基础网络是resnet18

**Comment by pycoco** [comment]
多谢

**Comment by pycoco** [comment]
还想问一下，为什么识别模型最后一层卷积通道数是79呢？

**Comment by xiangweizeng** [comment]
可以看成滑动窗口 + 分类问题， 79表示字符类别，主要是字母加省份

**Comment by pycoco** [comment]
多谢，还有个问题想跟你请教一下，最后一层卷积出来的特征图w得和设定的最大序列长度相同么?例如设定max_length=18,最后一层卷积出来的w维度也得是18
